#!/bin/bash
#-------------------------------------------------------------------------------------------------
#$Header: svn://localhost/dtapublic/projs/dtats/trunk/projs/2016/20161029_server_scripts_automaint_cron/daemons_down_premaint 71 2016-11-05 11:07:06Z dashley $
#-------------------------------------------------------------------------------------------------
#This file is part of "Server Scripts, Automatic Maintenance, Cron", a set of scripts for
#performing automatic periodic maintenance on a Linux server.
#-------------------------------------------------------------------------------------------------
#This source code and any program in which it is compiled/used is provided under the MIT License,
#reproduced below.
#-------------------------------------------------------------------------------------------------
#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files(the "Software"), to deal in the
#Software without restriction, including without limitation the rights to use,
#copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the
#Software, and to permit persons to whom the Software is furnished to do so,
#subject to the following conditions :
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#-------------------------------------------------------------------------------------------------
#Killing the daemons that might interfere with backups.
#
echo "Shutting down the daemons that might interfere with backups or other maintenance"
echo "activities."
#
wall "User Warning:  Daemons going down for maintenance in 2 minutes."
sleep 60
wall "User Warning:  Daemons going down for maintenance in 1 minute."
sleep 60
systemctl stop xinetd
sleep 30
systemctl stop httpd
#Allow lots of time because if there is a TCP connection still active and an SVN
#operation is going on, would prefer not to back up while this is going on.  The
#method is not 100% reliable, but should be OK for a small installation where
#SVN operations don't normally take very long.
sleep 120
#
#End of script.
