#!/bin/bash
#-------------------------------------------------------------------------------------------------
#$Header: svn://localhost/dtapublic/projs/dtats/trunk/projs/2016/20161029_server_scripts_automaint_cron/ref_dta_weekly 71 2016-11-05 11:07:06Z dashley $
#-------------------------------------------------------------------------------------------------
#This file is part of "Server Scripts, Automatic Maintenance, Cron", a set of scripts for
#performing automatic periodic maintenance on a Linux server.
#-------------------------------------------------------------------------------------------------
#This source code and any program in which it is compiled/used is provided under the MIT License,
#reproduced below.
#-------------------------------------------------------------------------------------------------
#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files(the "Software"), to deal in the
#Software without restriction, including without limitation the rights to use,
#copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the
#Software, and to permit persons to whom the Software is furnished to do so,
#subject to the following conditions :
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#-------------------------------------------------------------------------------------------------
#Full weekly backup Dave Ashley's server content.
#
echo "Performing full weekly backup of all Dave Ashley's server content.  List of directories"
echo "and files backed up appears below."
#
#Make the directory.
mkdir /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}
#
#Tar up everything except for the backup symlinks themselves.
tar -c -v -z -h -f /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.files.tar.gz /hb/ashley_david_personal_01/full_weekly &>/hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.files.log.txt
#
#Tar up the symlinks.
tar -c -v -z -f /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.symlinks.tar.gz /hb/ashley_david_personal_01/full_weekly &>/hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.symlinks.log.txt
#
#Emit the log files to stdout so they go in the larger log.
echo "===== FILES ====="
cat /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.files.log.txt
echo "===== SYMLINKS ====="
cat /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}/${1}${5}${6}_${10}${13}${14}.symlinks.log.txt
#
#We want to be really careful with this next section because of
#the recursive rm.  Want to be sure the directory exists.
if [ -d /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14} ] ; then
   cd /hl/baks/ashley_david_personal_01/full_weekly/${1}${5}${6}_${10}${13}${14}
   split -b 650m ${1}${5}${6}_${10}${13}${14}.files.tar.gz
   XFILES=`ls -1 x*`
   for curfile in $XFILES
   do
      mv ${curfile} ${curfile}.bin
   done
   md5sum  ${1}${5}${6}_${10}${13}${14}.* x* >md5sums.txt
   sha1sum ${1}${5}${6}_${10}${13}${14}.* x* >sha1sums.txt
   rm ${1}${5}${6}_${10}${13}${14}.files.tar.gz
   cd ..
   rm -fR `ls -1t | sed -e '2,$!d'`
fi
#End of script.
